//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFriendRequest
    {
        public int FriendRequestID { get; set; }
        public int UserSent { get; set; }
        public int UserReceived { get; set; }
        public int FriendRequestStatus { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
