//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPostLike
    {
        public int PostLikeID { get; set; }
        public int PostLike { get; set; }
        public int UserLike { get; set; }
    
        public virtual tblPost tblPost { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
