//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMedia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblFriendRequests = new HashSet<tblFriendRequest>();
            this.tblFriendRequests1 = new HashSet<tblFriendRequest>();
            this.tblPosts = new HashSet<tblPost>();
            this.tblPostLikes = new HashSet<tblPostLike>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserUsername { get; set; }
        public string UserPassword { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int VisibleDate { get; set; }
        public string Gender { get; set; }
        public int VisibleGender { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFriendRequest> tblFriendRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFriendRequest> tblFriendRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPost> tblPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPostLike> tblPostLikes { get; set; }

        public string NameSurname
        {
            get
            {
                return $"{UserSurname} {UserName} >{UserUsername}<";
            }
        }

        public string InitialUser
        {
            get
            {
                char[] first = UserSurname.ToCharArray();
                char[] second = UserName.ToCharArray();
                return $"{first[0]}{second[0]}";
            }
        }
    }
}
